version: "3"

vars:
  BUCKET: "{{.BUCKET | default \"gs://diagramik-frontend/\"}}"

tasks:
  dev:
    desc: Start development server
    cmds:
      - npm run dev

  build:
    desc: Build production bundle
    cmds:
      - npm run build

  push:
    desc: Pushes the frontend to production bucket
    cmds:
      - gcloud storage rsync --recursive dist {{.BUCKET}}

  publish:
    desc: Deploy built assets to GCS bucket
    cmds:
      - task: build
      - task: push

  install:
    desc: Install npm dependencies
    cmds:
      - npm install
