formatter:
  type: basic
  pad_line_comments: 2
  trim_trailing_whitespace: true
  retain_line_breaks: true
  retain_line_breaks_single: true
  eof_newline: true
  force_array_style: block
  force_quote_style: double
