version: "3"

vars:
  REGISTRY_GHCR: "{{.REGISTRY_GHCR | default \"ghcr.io\"}}"
  REGISTRY_GAR: "{{.REGISTRY_GAR | default \"europe-west4-docker.pkg.dev/playground-449613/diagramik\"}}"
  TAG: "{{.TAG | default \"latest\"}}"
  DIAGRAMS_BUCKET: "{{.DIAGRAMS_BUCKET | default \"diagramik-diagrams\"}}"
  SCAN_REGISTRY: "{{.SCAN_REGISTRY | default \"\"}}"  # Empty = local images, otherwise ghcr/gar
  REGION: "{{.REGION | default \"europe-west4\"}}"
  PROJECT_ID: "{{.PROJECT_ID | default \"playground-449613\"}}"

includes:
  monolith:
    taskfile: _docker-service.taskfile.yml
    vars:
      SERVICE_NAME: application-monolith
      DOCKERFILE: django_monolith/Dockerfile
      CLOUDRUN_SERVICE_NAME: diagramik
      REGISTRY_GHCR: "{{.REGISTRY_GHCR}}"
      REGISTRY_GAR: "{{.REGISTRY_GAR}}"
      TAG: "{{.TAG}}"
      CACHE_FROM: "{{.CACHE_FROM | default \"application-monolith:latest\"}}"
      SCAN_REGISTRY: "{{.SCAN_REGISTRY}}"
      REGION: "{{.REGION}}"
      PROJECT_ID: "{{.PROJECT_ID}}"

  mcp:
    taskfile: _docker-service.taskfile.yml
    vars:
      SERVICE_NAME: diagramming-mcp
      DOCKERFILE: mcp_diagrams/Dockerfile
      CLOUDRUN_SERVICE_NAME: diagramik-mcp
      REGISTRY_GHCR: "{{.REGISTRY_GHCR}}"
      REGISTRY_GAR: "{{.REGISTRY_GAR}}"
      TAG: "{{.TAG}}"
      CACHE_FROM: "{{.CACHE_FROM | default \"diagramming-mcp:latest\"}}"
      SCAN_REGISTRY: "{{.SCAN_REGISTRY}}"
      REGION: "{{.REGION}}"
      PROJECT_ID: "{{.PROJECT_ID}}"

  agent:
    taskfile: agent/Taskfile.yml
    dir: agent

tasks:
  # === Python Environment ===
  sync:
    desc: Install all Python dependencies via uv
    cmds:
      - uv sync --all-groups

  fmt:
    desc: Auto-fix lint issues and format code
    cmds:
      - .venv/bin/ruff check . --fix
      - .venv/bin/ruff format .

  # === Aggregate Tasks (all services) ===
  build:
    desc: Build all backend Docker images
    deps:
      - monolith:build
      - mcp:build

  scan:
    desc: Scan all backend Docker images with Trivy
    deps:
      - monolith:scan
      - mcp:scan

  test:
    desc: Run all tests
    deps:
      - monolith:test
      - mcp:test
      - agent:test:unit

  push:
    desc: Push all backend Docker images to registries
    deps:
      - monolith:push
      - mcp:push

  push:ghcr:
    desc: Push all images to GitHub Container Registry
    deps:
      - monolith:push:ghcr
      - mcp:push:ghcr

  push:gar:
    desc: Push all images to Google Artifact Registry
    deps:
      - monolith:push:gar
      - mcp:push:gar

  publish:
    desc: Build, scan, and push all backend Docker images
    cmds:
      - task: build
      - task: scan
      - task: push

  deploy:
    desc: Deploy all backend services to Cloud Run (assumes images already pushed)
    deps:
      - monolith:deploy
      - mcp:deploy

  redeploy:
    desc: Build, push to GAR, and deploy all backend services to Cloud Run
    deps:
      - monolith:redeploy
      - mcp:redeploy

  tag:latest:
    desc: Tag all images as latest and push to GHCR
    deps:
      - monolith:tag:latest
      - mcp:tag:latest

  pull:latest:
    desc: Pull latest images from registry
    deps:
      - monolith:pull:latest
      - mcp:pull:latest

  dev:
    desc: Run all services in dev mode (use in separate terminals)
    deps:
      - monolith:dev
      - mcp:dev

  # === Django Monolith Custom Tasks ===
  monolith:dev:
    desc: Run Django dev server locally
    env:
      DEPLOYMENT_ENVIRONMENT: DEBUG
    cmds:
      - .venv/bin/python django_monolith/manage.py runserver 0.0.0.0:8000

  monolith:test:
    desc: Run Tests in monolith service directory
    dir: ./django_monolith/
    cmds:
      - ../.venv/bin/pytest -n auto --cov=. --cov-report=term-missing --cov-report=html -vv

  monolith:check:
    desc: Test Django settings for common deployment config errors
    cmds:
      - .venv/bin/python django_monolith/manage.py check

  monolith:check-prod:
    desc: Test Django production settings for deployment errors
    env:
      DJANGO_SECRET_KEY: "789123456123123123123123123123123123123123123123123123arstqwfpzxcv"  # Has to be long and have many unique chars
    cmds:
      - mkdir -p django_monolith/backend/temp_settings
      - cp -r django_monolith/backend/settings/* django_monolith/backend/temp_settings
      - cp -r django_monolith/backend/deployed_settings/* django_monolith/backend/temp_settings
      - .venv/bin/python django_monolith/manage.py check --deploy --fail-level WARNING --settings=backend.temp_settings
      - rm -r django_monolith/backend/temp_settings

  # === MCP Custom Tasks ===
  mcp:dev:
    desc: Run MCP diagram server locally
    env:
      BUCKET_NAME: "{{.DIAGRAMS_BUCKET}}"
    cmds:
      - .venv/bin/python mcp_diagrams/server.py

  mcp:test:
    desc: Run Tests in mcp service directory
    dir: ./mcp_diagrams/
    cmds:
      - ../.venv/bin/pytest --cov=. --cov-report=term-missing --cov-report=html -vv

  # === Agent Tasks ===
  agent:test:with-server:
    desc: Run agent integration tests with real MCP server
    env:
      BUCKET_NAME: "{{.DIAGRAMS_BUCKET}}"
      MCP_SERVICE_URL: http://localhost:8080
    vars:
      MCP_LOG: /tmp/mcp_server_integration.log
      MCP_PID_FILE: /tmp/mcp_server_integration.pid
      MAX_RETRIES: 30
      RETRY_DELAY: 1
    cmds:
      # Start MCP server in background
      - echo "Starting MCP server..."
      - bash -c '.venv/bin/python mcp_diagrams/server.py > {{.MCP_LOG}} 2>&1 & echo $! > {{.MCP_PID_FILE}}'
      - echo "MCP server process started with PID $(cat {{.MCP_PID_FILE}})"

      - defer: |
          bash -c '
          if [ -f {{.MCP_PID_FILE}} ]; then
            MCP_PID=$(cat {{.MCP_PID_FILE}})
            if kill -0 "$MCP_PID" 2>/dev/null; then
              echo "Stopping MCP server (PID: $MCP_PID)..."
              kill "$MCP_PID" 2>/dev/null || true
              wait "$MCP_PID" 2>/dev/null || true
              echo "MCP server stopped"
            else
              echo "MCP server (PID: $MCP_PID) already stopped"
            fi
          else
            echo "PID file not found"
          fi
          echo "Removing temp files..."
          rm -f {{.MCP_PID_FILE}} {{.MCP_LOG}}
          echo "Cleanup complete!"
          '

        # Poll server with retries
      - |
        bash -c '
        echo "Waiting for MCP server to be ready (max {{.MAX_RETRIES}} attempts)..."
        while [ {{ .MAX_RETRIES }} -gt 0 ]; do
          # Check if process is still running
          if ! kill -0 "$(cat {{.MCP_PID_FILE}})" 2>/dev/null; then
            echo "ERROR: MCP server process died"
            echo "Server logs:"
            cat {{.MCP_LOG}}
            exit 1
          fi

          # Try to connect to server
          if curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/health > /dev/null 2>&1 || \
             curl -s -f http://localhost:8080 > /dev/null 2>&1; then
            echo "MCP server is ready!"
            exit 0
          fi

          MAX_RETRIES=$((MAX_RETRIES + 1))
          echo "Server not ready yet, waiting {{.RETRY_DELAY}}s..."
          sleep {{.RETRY_DELAY}}
        done

        echo "ERROR: MCP server failed to become ready after {{.MAX_RETRIES}} attempts"
        echo "Server logs:"
        cat {{.MCP_LOG}}
        exit 1
        '

      # Run integration tests
      - echo "Running agent integration tests..."
      - cd agent && ../.venv/bin/pytest tests/ -v -m integration
      - echo "Integration tests completed"

