# Generated by Django 6.0.1 on 2026-02-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quota_limit_default",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Default diagram generation limit for new users",
                    ),
                ),
                (
                    "quota_period_default",
                    models.CharField(
                        choices=[
                            ("day", "Per Day"),
                            ("week", "Per Week"),
                            ("month", "Per Month"),
                        ],
                        default="day",
                        help_text="Default quota period for new users",
                        max_length=10,
                    ),
                ),
                (
                    "email_rate_limit",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Maximum emails per hour (registration/password reset)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
