# Generated by Django 6.0.1 on 2026-02-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_settings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="use_new_agent",
            field=models.BooleanField(
                default=False,
                help_text="Use new DSPy-based agent for diagram generation (hybrid DSPy + FastAgent)",
            ),
        ),
    ]
