# Generated by Django 6.0.1 on 2026-02-02 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        help_text="OAuth provider name (e.g., 'google', 'facebook')",
                        max_length=50,
                    ),
                ),
                (
                    "uid",
                    models.CharField(
                        help_text="User ID from the OAuth provider", max_length=255
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional profile data from provider",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Account",
                "verbose_name_plural": "Social Accounts",
                "indexes": [
                    models.Index(
                        fields=["provider", "uid"],
                        name="user_auth_s_provide_bb9370_idx",
                    )
                ],
                "unique_together": {("provider", "uid")},
            },
        ),
    ]
