# Generated by Django 6.0.1 on 2026-01-18 12:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("diagrams_assistant", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="diagramversion",
            old_name="file_uri",
            new_name="image_url",
        ),
    ]
