# Generated by Django 6.0.1 on 2026-01-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diagrams_assistant", "0002_rename_file_uri_diagramversion_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagram",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="diagramversion",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
