# Generated by Django 6.0.1 on 2026-01-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diagrams_assistant", "0003_alter_diagram_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="diagramversion",
            old_name="image_url",
            new_name="image_uri",
        ),
        migrations.AlterField(
            model_name="diagram",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="diagramversion",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
