# Generated by Django 6.0.1 on 2026-01-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "diagrams_assistant",
            "0004_rename_image_url_diagramversion_image_uri_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="diagram",
            name="agent_history",
            field=models.TextField(blank=True, default=""),
        ),
    ]
