# Generated by Django 6.0.1 on 2026-01-20 17:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diagrams_assistant", "0005_diagram_agent_history"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quota_limit",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Maximum number of diagram generations allowed per period",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("day", "Per Day"),
                            ("week", "Per Week"),
                            ("month", "Per Month"),
                        ],
                        default="day",
                        help_text="Time period for quota reset",
                        max_length=10,
                    ),
                ),
                (
                    "is_unlimited",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, user has unlimited diagram generations",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagram_quota",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Quota",
                "verbose_name_plural": "User Quotas",
            },
        ),
        migrations.CreateModel(
            name="DiagramGenerationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagram_generation_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="diagrams_as_user_id_031df4_idx",
                    )
                ],
            },
        ),
    ]
