# Generated by Django 6.0.1 on 2026-01-20 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diagrams_assistant", "0006_userquota_diagramgenerationlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="userquota",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diagram_quota",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
