# Generated by Django 6.0.1 on 2026-02-02 17:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("diagrams_assistant", "0008_alter_userquota_user"),
    ]

    operations = [
        # Use SeparateDatabaseAndState to remove models from Django state
        # without dropping the database tables (quota_management app now manages them)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name="diagramgenerationlog",
                    name="diagrams_as_user_id_031df4_idx",
                ),
                migrations.RemoveField(
                    model_name="diagramgenerationlog",
                    name="user",
                ),
                migrations.DeleteModel(
                    name="UserQuota",
                ),
                migrations.DeleteModel(
                    name="DiagramGenerationLog",
                ),
            ],
            database_operations=[
                # No database operations - tables are preserved for quota_management app
            ],
        ),
    ]
