# Generated by Django 6.0.1 on 2026-02-02 17:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Use SeparateDatabaseAndState to register models in Django state
        # without creating new tables (they already exist from diagrams_assistant app)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="UserQuota",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "quota_limit",
                            models.PositiveIntegerField(
                                default=10,
                                help_text="Maximum number of diagram generations allowed per period",
                            ),
                        ),
                        (
                            "period",
                            models.CharField(
                                choices=[
                                    ("day", "Per Day"),
                                    ("week", "Per Week"),
                                    ("month", "Per Month"),
                                ],
                                default="day",
                                help_text="Time period for quota reset",
                                max_length=10,
                            ),
                        ),
                        (
                            "is_unlimited",
                            models.BooleanField(
                                default=False,
                                help_text="If checked, user has unlimited diagram generations",
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "user",
                            models.OneToOneField(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="diagram_quota",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "User Quota",
                        "verbose_name_plural": "User Quotas",
                        "db_table": "diagrams_assistant_userquota",
                    },
                ),
                migrations.CreateModel(
                    name="DiagramGenerationLog",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "user",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="diagram_generation_logs",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "diagrams_assistant_diagramgenerationlog",
                        "ordering": ["-created_at"],
                        "indexes": [
                            models.Index(
                                fields=["user", "created_at"],
                                name="diagrams_as_user_id_031df4_idx",
                            )
                        ],
                    },
                ),
            ],
            database_operations=[
                # No database operations - tables already exist from diagrams_assistant app
            ],
        ),
    ]
